name: Digital Evidence Archive - main

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  deploy_to_dev:
    env:
      CONFIGNAME: 'dev'
      STAGE: 'cfidev'
      DOMAIN_PREFIX: 'deadev' 
    environment: dea-dev
    defaults:
      run:
        shell: bash
        working-directory: ./source
    name: Deploy DEA to CFI-Dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.82.1
        with:
          extra_args: --only-verified                            
      - name: Install
        uses: ./.github/actions/baseAction
      - name: Rush Build
        run: |
          node common/scripts/install-run-rush.js build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: GITHUBACTIONSESSION
          aws-region: ${{ secrets.AWS_REGION }}
      - name: cdk deploy
        run: |
          cd dea-main
          npm run cdk bootstrap aws://${{secrets.AWS_ACCT_NUMBER}}/${{secrets.AWS_REGION}}
          npm run cdk deploy
