name: Standalone DEA

on:
  workflow_dispatch: {}

permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

jobs:
  deploy:
    env:
      CONFIGNAME: 'sandbox'
      STAGE: 'cfideasandbox'
      DOMAIN_PREFIX: 'cfideasandbox'
    environment: dea-sandbox
    defaults:
      run:
        shell: bash
        working-directory: ./source
    name: Deploy DEACFI Sandbox
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Run TruffleHog secret scan
        uses: trufflesecurity/trufflehog@v3.95.2
        with:
          extra_args: --only-verified
      - name: Install dependencies
        uses: ./.github/actions/baseAction
      - name: Build application
        run: |
          node common/scripts/install-run-rush.js build
      - name: Run linting
        run: |
          node common/scripts/install-run-rush.js lint
      - name: Run unit tests
        run: node common/scripts/install-run-rush.js unit:only
      - name: Run CDK unit tests
        run: node common/scripts/install-run-rush.js cdkunit:only --to @aws/dea-main
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_SANDBOX_HOMS_TEAM }}
          role-session-name: GITHUBACTIONSESSION
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy CDK stack
        run: |
          cd dea-main
          npm run cdk bootstrap aws://${{secrets.AWS_ACCT_NUMBER_SANDBOX}}/${{secrets.AWS_REGION}}
          npm run cdk deploy
